'use client'
import Link from'next/link';import{useEffect,useState}from'react';import{useRouter}from'next/navigation';import{createClient}from'../../lib/supabase'
export default function Page(){const s=createClient(),router=useRouter();const[a,setA]=useState<any[]>([]),[msg,setMsg]=useState('Carregando...'),[busy,setBusy]=useState('');useEffect(()=>{load()},[])
async function load(){const{data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}const[{data:l},{data:b}]=await Promise.all([s.from('likes').select('from_user').eq('to_user',user.id),s.from('blocks').select('blocked_id').eq('blocker_id',user.id)]);const blocked=new Set((b||[]).map(x=>x.blocked_id));const ids=[...new Set((l||[]).map(x=>x.from_user).filter(x=>!blocked.has(x)))];if(!ids.length){setA([]);setMsg('Quando alguém curtir você, aparecerá aqui.');return}const{data:p}=await s.from('profiles').select('id,display_name,city,state').in('id',ids).eq('is_suspended',false);setA(p||[]);setMsg('')}
async function like(id:string){if(busy)return;setBusy(id);setMsg('Confirmando...');const{data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}
const{error}=await s.from('likes').insert({from_user:user.id,to_user:id});if(error&&error.code!=='23505'){setBusy('');setMsg(`Não foi possível curtir: ${error.message}`);return}
const lo=user.id<id?user.id:id,hi=user.id<id?id:user.id;const{data:m,error:me}=await s.from('matches').select('id').eq('user_a',lo).eq('user_b',hi).maybeSingle()
if(me||!m){setBusy('');setMsg('Curtida registrada. Aguarde um instante e tente novamente.');return}
setMsg('Deu Match ♥ Abrindo a conversa...');router.push(`/conversas/${m.id}`)}
return <main className="center"><section className="likes-shell"><div className="top"><Link href="/descobrir">ENTRE NÓS</Link><Link href="/premium">PREMIUM</Link></div><h1>Curtidas</h1><p className="likes-intro">Pessoas que demonstraram interesse em você.</p>{msg&&<p className="discover-message">{msg}</p>}<div className="likes-grid">{a.map(x=><div className="like-card" key={x.id}><div className="like-placeholder">♡</div><div><strong>{x.display_name}</strong><small>{[x.city,x.state].filter(Boolean).join(' • ')}</small><button className="match-button" disabled={!!busy} onClick={()=>like(x.id)}>{busy===x.id?'Confirmando...':'♥ Curtir de volta'}</button></div></div>)}</div><nav className="appnav"><Link href="/descobrir">Descobrir</Link><b>Curtidas</b><Link href="/conversas">Conversas</Link><Link href="/perfil">Perfil</Link></nav></section></main>}