'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../lib/supabase'
export default function Admin(){const s=createClient();const[ok,setOk]=useState<boolean|null>(null),[users,setUsers]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]),[pix,setPix]=useState<any[]>([]),[q,setQ]=useState(''),[msg,setMsg]=useState('Carregando painel...')
async function load(){const{data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}const{data:adm}=await s.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(!adm){setOk(false);setMsg('Acesso restrito a administradores.');return}setOk(true);const[a,b,c,d,e]=await Promise.all([s.from('profiles').select('id,display_name,city,state,is_verified,is_suspended,created_at').order('created_at',{ascending:false}),s.from('reports').select('id,reporter_id,reported_id,reason,details,status,created_at').order('created_at',{ascending:false}),s.from('plans').select('*').order('price_cents'),s.from('subscriptions').select('*').order('created_at',{ascending:false}),s.from('pix_payments').select('*').order('created_at',{ascending:false})]);if([a,b,c,d,e].some(x=>x.error)){setMsg('Não foi possível carregar todos os dados do painel.');return}setUsers(a.data||[]);setReports(b.data||[]);setPlans(c.data||[]);setSubs(d.data||[]);setPix(e.data||[]);setMsg('')}
useEffect(()=>{load()},[])
async function suspend(id:string,v:boolean){if(!confirm(v?'Suspender este usuário?':'Reativar este usuário?'))return;const{error}=await s.rpc('admin_set_suspended',{target_user:id,suspended:v});if(error)return alert('Não foi possível concluir a ação.');setUsers(x=>x.map(u=>u.id===id?{...u,is_suspended:v}:u))}
async function status(id:string,v:string){const{error}=await s.rpc('admin_set_report_status',{target_report:id,new_status:v});if(error)return alert('Não foi possível atualizar a denúncia.');setReports(x=>x.map(r=>r.id===id?{...r,status:v}:r))}
async function price(p:any){const promo=prompt('Preço promocional em R$',(p.price_cents/100).toFixed(2).replace('.',','));if(promo===null)return;const normal=prompt('Preço normal em R$',(p.regular_price_cents/100).toFixed(2).replace('.',','));if(normal===null)return;const a=Math.round(Number(promo.replace(',','.'))*100),b=Math.round(Number(normal.replace(',','.'))*100);if(!Number.isFinite(a)||!Number.isFinite(b))return alert('Preço inválido.');const{error}=await s.rpc('admin_update_plan_prices',{target_plan:p.id,new_price_cents:a,new_regular_price_cents:b});if(error)return alert('Não foi possível alterar o preço.');setPlans(x=>x.map(y=>y.id===p.id?{...y,price_cents:a,regular_price_cents:b}:y))}
const name=(id:string)=>users.find(x=>x.id===id)?.display_name||'Usuário';const filtered=useMemo(()=>users.filter(u=>(u.display_name||'').toLowerCase().includes(q.toLowerCase())||(u.city||'').toLowerCase().includes(q.toLowerCase())),[users,q]);const money=(v:number)=>`R$ ${(v/100).toFixed(2).replace('.',',')}`
if(ok===false)return <main className="center"><section className="likes-shell"><h1>Painel administrativo</h1><p className="notice">{msg}</p><Link className="btn" href="/perfil">Voltar</Link></section></main>
return <main className="center"><section className="profile-editor" style={{width:'min(1000px,100%)'}}><div className="top"><Link href="/perfil">← PERFIL</Link><span>ADMIN • ENTRE NÓS</span></div><h1 style={{marginTop:28}}>Painel administrativo</h1><p>Usuários, denúncias, Premium e pagamentos.</p>{msg&&<p className="notice">{msg}</p>}{ok&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,margin:'24px 0'}}><div className="notice"><b>{users.length}</b><br/>Usuários</div><div className="notice"><b>{reports.filter(x=>x.status==='open').length}</b><br/>Denúncias abertas</div><div className="notice"><b>{subs.filter(x=>x.status==='active').length}</b><br/>Premium ativos</div><div className="notice"><b>{pix.filter(x=>x.status==='paid').length}</b><br/>PIX pagos</div></div>
<h2>Premium</h2>{plans.map(p=><div key={p.id} style={{border:'1px solid #4f2b35',borderRadius:16,padding:16,marginBottom:12}}><b>{p.name}</b><p>Oferta: <strong>{money(p.price_cents)}</strong> • Normal: {money(p.regular_price_cents)} • {p.duration_days} dias</p><button className="btn" onClick={()=>price(p)}>Alterar preços</button></div>)}
<h2 style={{marginTop:30}}>Denúncias</h2><div style={{display:'grid',gap:12}}>{reports.length?reports.map(r=><article key={r.id} style={{border:'1px solid #4f2b35',borderRadius:16,padding:16}}><b>{name(r.reported_id)}</b><p>{r.reason}{r.details?` — ${r.details}`:''}</p><small>Status: {r.status}</small><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button className="btn" onClick={()=>status(r.id,'reviewing')}>Em análise</button><button className="btn" onClick={()=>status(r.id,'resolved')}>Resolver</button><button className="btn" onClick={()=>status(r.id,'dismissed')}>Descartar</button></div></article>):<p className="notice">Nenhuma denúncia.</p>}</div>
<h2 style={{marginTop:30}}>Usuários</h2><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome ou cidade" style={{width:'100%',height:48,borderRadius:12,border:'1px solid #5c303b',background:'#0d090a',color:'white',padding:'0 14px',marginBottom:14}}/><div style={{display:'grid',gap:10}}>{filtered.map(u=><div key={u.id} style={{border:'1px solid #4f2b35',borderRadius:16,padding:14,display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap'}}><div><b>{u.display_name||'Usuário'}</b><small style={{display:'block',color:'#b7a8ac',marginTop:5}}>{[u.city,u.state].filter(Boolean).join(' • ')||'Local não informado'} {u.is_suspended?'• SUSPENSO':''}</small></div><button className={u.is_suspended?'btn':'btn primary'} onClick={()=>suspend(u.id,!u.is_suspended)}>{u.is_suspended?'Reativar':'Suspender'}</button></div>)}</div>
<h2 style={{marginTop:30}}>Pagamentos PIX</h2>{pix.length?<div style={{display:'grid',gap:10}}>{pix.map(x=><div key={x.id} className="notice"><b>{name(x.user_id)}</b> • {money(x.amount_cents)} • {x.status}</div>)}</div>:<p className="notice">Nenhum pagamento PIX registrado ainda.</p>}</>}</section></main>}