'use client'
import Link from'next/link'
import{ChangeEvent,FormEvent,useEffect,useState}from'react'
import{createClient}from'../../lib/supabase'
const UFS=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO']
const OPTIONS=['Música','Filmes e séries','Viagens','Gastronomia','Esportes','Natureza','Leitura','Pets','Arte','Tecnologia']
export default function Perfil(){const s=createClient();const[n,setN]=useState(''),[c,setC]=useState(''),[uf,setUf]=useState(''),[b,setB]=useState(''),[looking,setLooking]=useState(''),[interests,setInterests]=useState<string[]>([]),[m,setM]=useState('Carregando...'),[photo,setPhoto]=useState(''),[uploading,setUploading]=useState(false)
useEffect(()=>{(async()=>{const{data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}const[{data:p},{data:ph}]=await Promise.all([s.from('profiles').select('display_name,city,state,bio,looking_for,interests').eq('id',user.id).single(),s.from('profile_photos').select('storage_path').eq('user_id',user.id).eq('position',0).maybeSingle()]);if(p){setN(p.display_name||'');setC(p.city||'');setUf(p.state||'');setB(p.bio||'');setLooking(p.looking_for||'');setInterests(p.interests||[])}if(ph?.storage_path){const{data:u}=await s.storage.from('profile-photos').createSignedUrl(ph.storage_path,3600);if(u?.signedUrl)setPhoto(u.signedUrl)}setM('')})()},[])
async function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setM('A foto deve ter no máximo 5 MB.');return}setUploading(true);const{data:{user}}=await s.auth.getUser();if(!user)return;const ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/principal-${Date.now()}.${ext}`;const{error}=await s.storage.from('profile-photos').upload(path,f);if(error){setM('Não foi possível enviar a foto.');setUploading(false);return}const{data:old}=await s.from('profile_photos').select('storage_path').eq('user_id',user.id).eq('position',0).maybeSingle();await s.from('profile_photos').upsert({user_id:user.id,storage_path:path,position:0},{onConflict:'user_id,position'});if(old?.storage_path)await s.storage.from('profile-photos').remove([old.storage_path]);const{data:u}=await s.storage.from('profile-photos').createSignedUrl(path,3600);setPhoto(u?.signedUrl||'');setM('Foto atualizada.');setUploading(false)}
function toggle(x:string){setInterests(v=>v.includes(x)?v.filter(i=>i!==x):v.length<5?[...v,x]:v)}
async function save(e:FormEvent){e.preventDefault();if(!photo){setM('Adicione uma foto para aparecer em Descobrir.');return}if(!c.trim()||!uf||!b.trim()||!looking){setM('Complete os campos obrigatórios.');return}setM('Salvando...');const{data:{user}}=await s.auth.getUser();if(!user)return;const{error}=await s.from('profiles').update({display_name:n,city:c.trim(),state:uf,bio:b.trim(),looking_for:looking,interests,avatar_url:photo,updated_at:new Date().toISOString()}).eq('id',user.id);setM(error?'Não foi possível salvar o perfil.':'Perfil salvo com sucesso.')}
async function sair(){if(!confirm('Deseja sair da sua conta?'))return;await s.auth.signOut();location.href='/entrar'}
const field={width:'100%',boxSizing:'border-box' as const,border:'1px solid #63313e',borderRadius:14,background:'#0b0809',color:'#fff',padding:'13px 14px',fontSize:16}
return <main className="center"><section className="profile-editor"><div className="top"><Link href="/descobrir">ENTRE NÓS</Link><Link href="/premium">PREMIUM</Link></div><div className="profile-heading"><div><h1>Meu perfil</h1><p>Complete os campos obrigatórios (*) para aparecer em Descobrir.</p></div><label className="avatar-upload">{photo?<img src={photo} alt="Foto do perfil"/>:<span>♡</span>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading}/><b>{uploading?'Enviando...':photo?'Trocar foto':'Adicionar foto *'}</b></label></div>
<form className="profile-form" onSubmit={save}><label>Nome ou apelido *<input value={n} onChange={e=>setN(e.target.value)} required/></label><div className="profile-row"><label>Cidade *<input value={c} onChange={e=>setC(e.target.value)} required/></label><label>Estado *<select value={uf} onChange={e=>setUf(e.target.value)} required style={field}><option value="">UF</option>{UFS.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Sobre você *<textarea value={b} onChange={e=>setB(e.target.value)} maxLength={500} required/></label>
<label>O que você procura? *<select value={looking} onChange={e=>setLooking(e.target.value)} required style={field}><option value="">Selecione</option><option value="conversa">Boas conversas</option><option value="amizade">Amizade</option><option value="relacionamento">Relacionamento</option><option value="ainda_nao_sei">Ainda não sei</option></select></label>
<div style={{marginTop:8}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:12}}><strong>Interesses</strong><small style={{color:'#c99aa6'}}>{interests.length}/5 selecionados</small></div><div style={{display:'flex',flexWrap:'wrap',gap:10}}>{OPTIONS.map(x=>{const on=interests.includes(x),disabled=!on&&interests.length>=5;return <button key={x} type="button" disabled={disabled} onClick={()=>toggle(x)} aria-pressed={on} style={{width:'auto',minWidth:0,padding:'10px 15px',borderRadius:999,border:on?'1px solid #d35a7d':'1px solid #63313e',background:on?'#7c203b':'#160e11',color:disabled?'#735e64':'#fff',fontSize:14,cursor:disabled?'not-allowed':'pointer',opacity:disabled?.55:1}}>{on?'✓ ':''}{x}</button>})}</div></div>
{m&&<p className="notice">{m}</p>}<button className="btn primary save-profile">Salvar perfil</button></form><div style={{marginTop:18,display:'grid',gap:12,textAlign:'center'}}><Link className="btn" href="/bloqueados">Usuários bloqueados</Link><button type="button" className="btn primary" onClick={sair}>Sair da conta</button></div><nav className="appnav"><Link href="/descobrir">Descobrir</Link><Link href="/curtidas">Curtidas</Link><Link href="/conversas">Conversas</Link><b>Perfil</b></nav></section></main>}