'use client'
import Link from 'next/link'
import {ChangeEvent,FormEvent,useEffect,useState} from'react'
import{createClient}from'../../lib/supabase'
export default function Perfil(){const s=createClient();const[n,setN]=useState(''),[c,setC]=useState(''),[uf,setUf]=useState(''),[b,setB]=useState(''),[m,setM]=useState('Carregando...');const[photo,setPhoto]=useState(''),[uploading,setUploading]=useState(false)
useEffect(()=>{(async()=>{const{data:{user}}=await s.auth.getUser();if(!user){location.href='/entrar';return}const[{data:p},{data:ph}]=await Promise.all([s.from('profiles').select('display_name,city,state,bio').eq('id',user.id).single(),s.from('profile_photos').select('storage_path').eq('user_id',user.id).eq('position',0).maybeSingle()]);if(p){setN(p.display_name||'');setC(p.city||'');setUf(p.state||'');setB(p.bio||'')}if(ph?.storage_path)setPhoto(s.storage.from('profile-photos').getPublicUrl(ph.storage_path).data.publicUrl);setM('')})()},[])
async function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setM('A foto deve ter no máximo 5 MB.');return}setUploading(true);const{data:{user}}=await s.auth.getUser();if(!user)return;const ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/principal-${Date.now()}.${ext}`;const{error}=await s.storage.from('profile-photos').upload(path,f);if(error){setM('Não foi possível enviar a foto.');setUploading(false);return}const{data:old}=await s.from('profile_photos').select('storage_path').eq('user_id',user.id).eq('position',0).maybeSingle();await s.from('profile_photos').upsert({user_id:user.id,storage_path:path,position:0},{onConflict:'user_id,position'});if(old?.storage_path)await s.storage.from('profile-photos').remove([old.storage_path]);setPhoto(s.storage.from('profile-photos').getPublicUrl(path).data.publicUrl);setM('Foto atualizada com sucesso.');setUploading(false)}
async function save(e:FormEvent){e.preventDefault();setM('Salvando...');const{data:{user}}=await s.auth.getUser();if(!user)return;const{error}=await s.from('profiles').update({display_name:n,city:c,state:uf,bio:b,avatar_url:photo||null,updated_at:new Date().toISOString()}).eq('id',user.id);setM(error?'Erro: '+error.message:'Perfil salvo com sucesso.')}
async function sair(){if(!confirm('Deseja sair da sua conta?'))return;setM('Saindo...');const{error}=await s.auth.signOut();if(error){setM('Não foi possível sair. Tente novamente.');return}location.href='/entrar'}
return <main className="center"><section className="profile-editor"><div className="top"><Link href="/descobrir">ENTRE NÓS</Link><Link href="/premium">PREMIUM</Link></div><div className="profile-heading"><div><h1>Meu perfil</h1><p>Complete seus dados para aparecer em Descobrir.</p></div><label className="avatar-upload">{photo?<img src={photo} alt="Foto do perfil"/>:<span>♡</span>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading}/><b>{uploading?'Enviando...':photo?'Trocar foto':'Adicionar foto'}</b></label></div><form className="profile-form" onSubmit={save}><label>Nome ou apelido<input value={n} onChange={e=>setN(e.target.value)} required/></label><div className="profile-row"><label>Cidade<input value={c} onChange={e=>setC(e.target.value)}/></label><label className="state-field">Estado<input value={uf} onChange={e=>setUf(e.target.value.toUpperCase())} maxLength={2}/></label></div><label>Sobre você<textarea value={b} onChange={e=>setB(e.target.value)} maxLength={500}/></label>{m&&<p className="notice">{m}</p>}<button className="btn primary save-profile">Salvar perfil</button></form><div style={{marginTop:18,display:'grid',gap:12,textAlign:'center'}}><Link className="btn" href="/bloqueados">Usuários bloqueados</Link><button type="button" className="btn primary" onClick={sair}>Sair da conta</button></div><nav className="appnav"><Link href="/descobrir">Descobrir</Link><Link href="/curtidas">Curtidas</Link><Link href="/conversas">Conversas</Link><b>Perfil</b></nav></section></main>}